import SessionWrapper from '@/components/SessionWrapper';
import '../styles/globals.css';
import LayoutDefault from '@/components/layout/LayoutDefault.tsx/LayoutDefault';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body>
          <div className='flex justify-center'>
            <LayoutDefault>{children}</LayoutDefault>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
