import SessionWrapper from '@/components/SessionWrapper';
import '../styles/globals.css';
import LayoutDefault from '@/components/layout/LayoutDefault.tsx/LayoutDefault';
import { MantineProvider } from '@mantine/core';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body suppressHydrationWarning={false}>
          <div className='flex justify-center'>
            <MantineProvider>
              <LayoutDefault>{children}</LayoutDefault>
            </MantineProvider>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
