import SessionWrapper from '@/components/SessionWrapper';
import '../styles/globals.css';
import LayoutDefault from '@/components/layout/LayoutDefault.tsx/LayoutDefault';
import { MantineProvider, createTheme } from '@mantine/core';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body suppressHydrationWarning={false}>
          <div className='flex justify-center'>
            <MantineProvider theme={theme}>
              <LayoutDefault>{children}</LayoutDefault>
            </MantineProvider>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
